# Exercise 1 

In this exercise, we will go over an object-oriented programming exercises related to standard operations with `pandas` data frames. 

### Exercise 1(a) (10 points)

Create a class called `DataFrameProcessor` that will handle basic operations on a pandas DataFrame. Your class should:

1. Initialize with a pandas DataFrame.
2. Have a method get_column_stats(column_name) that returns the mean, median, and standard deviation of the specified column.
3. Have a method filter_rows(column_name, threshold) that returns a new DataFrame with rows where the values in the specified column are greater than the given threshold.
4. Have a method add_new_column(column_name, data) that adds a new column with the specified name and data to the DataFrame.

In [1]:
class DataFrameProcessor:
    def __init__(self, dataframe):
        """Initialize the DataFrameProcessor with a pandas DataFrame."""
        self.dataframe = dataframe

    def get_column_stats(self, column_name):
        """ Return the mean, median, and standard deviation of the specified column."""
        mean_value = self.dataframe[column_name].mean()
        median_value = self.dataframe[column_name].median()
        std_value = self.dataframe[column_name].std()

        return {
            "mean": mean_value,
            "median": median_value,
            "std": std_value
        }

    def filter_rows(self, column_name, threshold):
        """Return a DataFrame with rows where the specified column's value is greater than the threshold."""
        return self.dataframe[self.dataframe[column_name] > threshold]

    def add_new_column(self, column_name, data):
        """Add a new column to the DataFrame with the specified data."""
        self.dataframe[column_name] = data
        return self.dataframe

### Exercise 1(b) (3 points)

Create a data frame called `df` with three columns and 20 rows. Fill the data frame with random integers from 1 to 20. Hint: use `np.random.randint` from `numpy` to generate the random integers.

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Col_1": np.random.randint(1, 20, 20),
    "Col_2": np.random.randint(1, 20, 20),
    "Col_3": np.random.randint(1, 20, 20)
})

df

    Col_1  Col_2  Col_3
0      19      8     10
1       4     17      3
2       6     16      4
3      10     12      2
4      10      8     19
5      12     18      7
6       2     17      1
7       1     18      8
8      17      4     18
9      10      6     11
10      8     16      6
11     14      8      1
12      2      7     12
13     10     19      7
14      8      6      5
15     10      3      9
16     10      1      1
17     19     19     18
18     10     14     17
19     14     15     17

### Exercise 1(c) (4 points)

Using the `DataFrameProcessor` class, report the stats for each of the columns in `df`.

In [3]:
# Initialization of the DataFrameProcessor with the created DataFrame
df_processor = DataFrameProcessor(df)

# Report the statistics for each of the columns
for col in df.columns:
    print(f"Processing column: {col}")
    stats = df_processor.get_column_stats(col)
    print(f"Statistics for {col}: {stats}")
    print("-" * 40)

Processing column: Col_1
Statistics for Col_1: {'mean': 9.8, 'median': 10.0, 'std': 5.20728235010204}
----------------------------------------
Processing column: Col_2
Statistics for Col_2: {'mean': 11.6, 'median': 13.0, 'std': 5.950674442093893}
----------------------------------------
Processing column: Col_3
Statistics for Col_3: {'mean': 8.8, 'median': 7.5, 'std': 6.2374083686972694}
----------------------------------------

### Exercise 1(d) (3 points)

Filter the rows where `col_3` is greater than 12.

In [5]:
print(f"The rows where Col_3 is greater than 12 are:\n{df_processor.filter_rows('Col_3', 12)}")

The rows where Col_3 is greater than 12 are:
    Col_1  Col_2  Col_3
4      10      8     19
8      17      4     18
17     19     19     18
18     10     14     17
19     14     15     17

### Exercise 1(e) (3 points)

Create a list with random intergers from 1 to 20. Add the list to `df` as new column called `col_4`.

In [ ]:
# Creating a new column in the DataFrame
new_data = np.random.randint(1, 20, 20)

# Adding the new column to the df_processor
df_processor.add_new_column("Col_4", new_data)
print(f"Added new column 'Col_4' with data:\n{df_processor.dataframe}")

Added new column 'Col_4' with data:
    Col_1  Col_2  Col_3  Col_4
0      19      8     10     12
1       4     17      3     13
2       6     16      4     10
3      10     12      2      3
4      10      8     19     14
5      12     18      7     14
6       2     17      1     17
7       1     18      8     18
8      17      4     18      2
9      10      6     11     19
10      8     16      6      1
11     14      8      1     12
12      2      7     12      8
13     10     19      7      3
14      8      6      5     16
15     10      3      9      3
16     10      1      1      6
17     19     19     18      5
18     10     14     17      8
19     14     15     17     19

# Exercise 2 (10 points)

Data pre-processing with OOP. Create a Python class called `DataPreprocessor` that:

1. Takes a pandas DataFrame as input.
2. Provides methods to:
   - Handle missing values by filling them with the column mean.
   - Normalize numerical columns between 0 and 1.
3. Returns the cleaned DataFrame when called with `.transform()`

Consider `df` as DataFrame to test the class.

```
data = {
    "age": [25, np.nan, 35, 40, np.nan],
    "income": [50000, 60000, np.nan, 80000, 75000],
    "gender": ["M", "F", "M", "F", "M"]
}
df = pd.DataFrame(data)
```

In [11]:
class DataPreprocessor:
    def __init__(self, dataframe):
        """Initializes the DataPreprocessor with the given DataFrame."""
        self.dataframe = dataframe

    def filling_missing_values(self):
        """ Fills the missing values of a given columnin the DataFrame with the column mean.""" 
        for col in self.dataframe.select_dtypes(include=[np.number]).columns:
            self.dataframe[col] = self.dataframe[col].fillna(self.dataframe[col].mean())
        return self 

    def normalize(self):
        """ Normalizes the numeric columns in the DataFrame to the range [0, 1]."""
        for col in self.dataframe.select_dtypes(include=[np.number]).columns:
            col_min = self.dataframe[col].min()
            col_max = self.dataframe[col].max()
            self.dataframe[col] = (self.dataframe[col] - col_min) / (col_max - col_min)
        return self

    def transform(self):
        return self.dataframe

# Example usage:
data = pd.DataFrame({
    "age": [25, np.nan, 35, 40, np.nan],
    "income": [50000, 60000, np.nan, 80000, 75000],
    "graduated": ["Yes", "No", "Yes", "No", "Yes"]
})

print("Original DataFrame:")
print(data)

# Initialize the data preprocessor with the original data
preprocessor = DataPreprocessor(data)
processed_data = preprocessor.filling_missing_values().normalize().transform()

print("\nProcessed DataFrame:")
print(processed_data)

Original DataFrame:
    age   income graduated
0  25.0  50000.0       Yes
1   NaN  60000.0        No
2  35.0      NaN       Yes
3  40.0  80000.0        No
4   NaN  75000.0       Yes

Processed DataFrame:
        age    income graduated
0  0.000000  0.000000       Yes
1  0.555556  0.333333        No
2  0.666667  0.541667       Yes
3  1.000000  1.000000        No
4  0.555556  0.833333       Yes

# Exercise 3 

In this exercise, we will practice `merge` with `pandas` data frames. Merging in `pandas` is a way of combining two data frames based on a common column or set of columns. Think of it like putting together pieces of a puzzle where both tables have a shared piece of information (like a key or ID number) that helps you connect the rows that belong together.

### Exercise 3(a) (2 points)

Load the `pandas` library.

In [12]:
import pandas as pd

### Exercise 3(b) (4 points)

Create three `pandas` data-frames based on the following raw data:

```
raw_data_1 = {
        'subject_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'], 
        'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}

raw_data_2 = {
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}

raw_data_3 = {
        'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
        'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}
```

Call them `dat_1`, `dat_2`, and `dat_3`, respectively.

In [13]:
raw_data_1 = {
        'subject_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'], 
        'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}

raw_data_2 = {
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}

raw_data_3 = {
        'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
        'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}

dat_1 = pd.DataFrame(raw_data_1)
dat_2 = pd.DataFrame(raw_data_2)
dat_3 = pd.DataFrame(raw_data_3)

In [14]:
dat_1

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches

In [15]:
dat_2

  subject_id first_name last_name
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [16]:
dat_3

  subject_id  test_id
0          1       51
1          2       15
2          3       15
3          4       61
4          5       16
5          7       14
6          8       15
7          9        1
8         10       61
9         11       16

### Exercise 3(c) (3 points)

Combine `dat_1` and `dat_2` along the rows and call the resulting data frame `all_data`.

In [18]:
all_data = pd.concat([dat_1, dat_2], axis=0).reset_index(drop=True)
all_data

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
5          4      Billy    Bonder
6          5      Brian     Black
7          6       Bran   Balwner
8          7      Bryce     Brice
9          8      Betty    Btisan

### Exercise 3(d) (3 points)

Combine `dat_1` and `dat_2` along the columns and call the resulting data frame `all_data_col`.

In [19]:
all_data_col = pd.concat([dat_1, dat_2], axis=1)
all_data_col

  subject_id first_name last_name subject_id first_name last_name
0          1       Alex  Anderson          4      Billy    Bonder
1          2        Amy  Ackerman          5      Brian     Black
2          3      Allen       Ali          6       Bran   Balwner
3          4      Alice      Aoni          7      Bryce     Brice
4          5     Ayoung   Atiches          8      Betty    Btisan

### Exercise 3(e) (3 points)

Merge `all_data` and `dat_3` using `subject_id` as the key variable, and call the resulting data frame `dat_merge`.

In [20]:
all_data

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
5          4      Billy    Bonder
6          5      Brian     Black
7          6       Bran   Balwner
8          7      Bryce     Brice
9          8      Betty    Btisan

In [21]:
dat_3

  subject_id  test_id
0          1       51
1          2       15
2          3       15
3          4       61
4          5       16
5          7       14
6          8       15
7          9        1
8         10       61
9         11       16

In [22]:
data_merge = pd.merge(all_data, dat_3, on="subject_id")
data_merge

  subject_id first_name last_name  test_id
0          1       Alex  Anderson       51
1          2        Amy  Ackerman       15
2          3      Allen       Ali       15
3          4      Alice      Aoni       61
4          5     Ayoung   Atiches       16
5          4      Billy    Bonder       61
6          5      Brian     Black       16
7          7      Bryce     Brice       14
8          8      Betty    Btisan       15

### Exercise 3(f) (3 points)

Merge `dat_1` and `dat_2` using `subject_id` as the key variable, and call the resulting data frame `dat_merge_1`.

In [23]:
dat_merge_1 = pd.merge(dat_1, dat_2, on="subject_id")
dat_merge_1

  subject_id first_name_x last_name_x first_name_y last_name_y
0          4        Alice        Aoni        Billy      Bonder
1          5       Ayoung     Atiches        Brian       Black

### Exercise 3(g) (3 points)

Merge all the values in `dat_1` and `dat_2`, using `subject_id` as the key variable, with matching records from the left data frame. Call the resulting data frame `dat_merge_2`.

In [24]:
dat_merge_2 = pd.merge(dat_1, dat_2, on="subject_id", how="left")
dat_merge_2

  subject_id first_name_x last_name_x first_name_y last_name_y
0          1         Alex    Anderson          NaN         NaN
1          2          Amy    Ackerman          NaN         NaN
2          3        Allen         Ali          NaN         NaN
3          4        Alice        Aoni        Billy      Bonder
4          5       Ayoung     Atiches        Brian       Black

# Exercise 4

In this exercise, we will practice functional programming with `pandas` data frame. Functional programming concepts with `pandas` involves using `apply()`, `map()`, and `lambda()` functions. 

### Exercise 4(a) (3 points)

Imagine you are working with a data set of customers that includes their purchase amounts in different categories. The goal is to apply transformations and extract insights using functional programming techniques. Create the below `pandas` data frame.

```
import pandas as pd

data = {
    'Customer_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Groceries': [120, 150, 80, 90, 130],
    'Electronics': [200, 0, 100, 300, 150],
    'Clothing': [50, 60, 45, 70, 30]
}

df = pd.DataFrame(data)
```

### Exercise 4(b) (3 points)

Use the `apply()` function to calculate the total spending for each customer (sum of `Groceries`, `Electronics`, and `Clothing`).

### Exercise 4(c) (3 points)

Use a `lambda` function to classify customers as `High`, `Medium`, or `Low` spenders based on their total spending:

- High: Total spending >= 400
- Medium: Total spending between 200 and 399
- Low: Total spending < 200

### Exercise 4(d) (3 points)

Calculate the percentage of spending in `Electronics` compared to the `Total_Spend` for each customer.

### Exercise 4(e) (4 points)

Write a custom function that can be passed to `apply()` to give a 10% discount on electronics spending if a customer's total spend is above $400.